### ISSUE TITLE
Detailed info about a score of a news entry should display tag names instead of uids

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/feeds.fun#109]

**Comment by AnuravModak** [comment]
can u provide description???

**Comment by Tiendil** [comment]
Hi! 

Thank you for your interest in the project :-)

![feeds-fun-wrong-tag-name-in-score-details](https://github.com/Tiendil/feeds.fun/assets/871672/d34e6b6a-1ccb-412b-9b4a-326216296cea)

I hope this screenshot will be helpful.

The functionality to show score & dialog is here: https://github.com/Tiendil/feeds.fun/blob/main/site/src/values/Score.vue

**Comment by Tiendil** [comment]
An example of how to get tag info by tag id: https://github.com/Tiendil/feeds.fun/blob/c2e9d53638fd9e198c76681f10b8e27bcd47e373/site/src/components/TagsFilter.vue#L114-L122
