### ISSUE TITLE
Nothing changes when we try to create a duplicated rule from the news view

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/feeds.fun#112]
Attempt to create a duplicated rule from the news view should show an error or successfully update the rule's score

**Comment by AnuravModak** [comment]
if its not taken can u assign me this and any related information or description about this will help. @Tiendil

**Comment by Tiendil** [comment]
Thank you for your interest in the project!

Here is some info.

How to reproduce:

- Go to the news page.
- Create a rule with tags `A, B` and a score `X`.
- Go to the rules page, see that the rule is there with the score `X`.
- Return to the news page.
- Try to create a rule with the same tags `A, B` but a score `Y`.
- Go to the rules page, see that the rule is there with the score `X` <-- this is the bug.

Expected result:

- The rule's score should be updated to `Y`.
- No notifications in the interface are required. Just silently update the score.

Places of interest in the code:

- API call from the frontend to creare a rule: https://github.com/Tiendil/feeds.fun/blob/09d4ed71fa67335add44616470b431e32eb38e71/site/src/logic/api.ts#L100
- API call from the frontend to update a rule: https://github.com/Tiendil/feeds.fun/blob/09d4ed71fa67335add44616470b431e32eb38e71/site/src/logic/api.ts#L113 Maybe it should be removed (with the backend implementation) because after fixing the bug it will duplicate the functionality of rule creation.
- Backend API implementation: https://github.com/Tiendil/feeds.fun/blob/main/ffun/ffun/api/http_handlers.py
- Backend rules implementation: https://github.com/Tiendil/feeds.fun/tree/main/ffun/ffun/scores

P.S. Feel free to create a draft pull request, I'll try to review it, maybe add a few suggestions at the beginning of the fix.

**Comment by AnuravModak** [comment]
ok, i will start working on it @Tiendil.

**Comment by AnuravModak** [comment]
Heyy @Tiendil, i think you need to unassign me because I work on my work laptop and it does not allow to install docker, so i have been trying that since last few days, its a non-compliant for my PC also currently i dont have my personal PC where I am situtated. I hope you understand. If I can work on anything else without installing docker please let me know.
